from enum import Enum

class RetrievalStrategy(str, Enum):
    DOCUMENT_QUERY = "DOCUMENT_QUERY"
    CONSULTATION_QUERY = "CONSULTATION_QUERY"
    APPOINTMENT_QUERY = "APPOINTMENT_QUERY"
    ASSET_INDEX_QUERY = "ASSET_INDEX_QUERY"
    PATIENT_HISTORY_QUERY = "PATIENT_HISTORY_QUERY"
    MEMORY_QUERY = "MEMORY_QUERY"
    DEEP_REASONING = "DEEP_REASONING"
    GENERAL_CHAT = "GENERAL_CHAT"
    DOCTOR_AVAILABILITY_QUERY = "DOCTOR_AVAILABILITY_QUERY"
